use School;

DROP TABLE student;
CREATE DATABASE School;
USE School;
CREATE TABLE STUDENT (
    Roll_No INT PRIMARY KEY,
    Name VARCHAR(50),
    Marks INT,
    Grade CHAR(1));
INSERT INTO STUDENT (Roll_No, Name, Marks, Grade) VALUES
(1, 'ABID', 85, 'A'),
(2, 'ALFAS', 78, 'B'),
(3, 'ASLAM', 90, 'A'),
(4, 'AAFIYA', 65, 'C');

SELECT * FROM STUDENT;
ALTER TABLE STUDENT
ADD COLUMN Contact VARCHAR(15);
RENAME TABLE STUDENT TO CLASSTEN;
TRUNCATE TABLE CLASSTEN;

DROP TABLE CLASSTEN;